### ISSUE TITLE
Trait not found

### ISSUE THREAD

**Issue by kevinvayro** [shalvah/laravel-jsend#8]
When I add the trait to `App\Exceptions\Handler` as shown in the docs I get the following error:

`Trait 'App\Exceptions\Shalvah\LaravelJsend\JsendExceptionFormatter' not found`

Can you please point out where I am going wrong with using it in this file?

**Comment by shalvah** [comment]
Add an initial \ before the name:

`use \Shalvah\LaravelJsend\JsendExceptionFormatter`

Without the slash (or an import), PHP thinks you're referencing a trait in the current namespace (`App\Exceptions`).
